# Generated by Django 4.0.3 on 2022-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
