# Generated by Django 4.0.3 on 2022-03-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='reservationInvitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=True)),
                ('invitees', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.employees')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.employees'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.rooms'),
        ),
    ]
